# Generated by Django 2.2.4 on 2019-08-09 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userlogin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlogin',
            name='password',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
