# Generated by Django 2.2.4 on 2019-08-09 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userlogin', '0003_userlogin_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlogin',
            name='phonenumber',
            field=models.IntegerField(null=True),
        ),
    ]
